# Generated by Django 5.2.15 on 2026-06-05 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('emoji', models.CharField(blank=True, default='📁', max_length=10)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color for charts (e.g. #6366f1)', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('confidence', models.FloatField(blank=True, help_text='OCR confidence percentage (0-100)', null=True)),
                ('payment', models.CharField(blank=True, default='', help_text='e.g. "Visa ····1234"', max_length=100)),
                ('location', models.CharField(blank=True, default='', help_text='e.g. "San Francisco, CA"', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='The uploaded receipt photo', null=True, upload_to='receipts/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='receipts.category')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receipts.receipt')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
